from tkinter import*
window = Tk()
window.title("Welcome to LikeGeeks app")
window.geometry('350x200')
greeting = Label(text="Hello, Tkinter", fg = "red", font = ("Helvetica", 16))
button = Button(window, text="Click Me", fg="blue",)
entry = Entry(window, width=10)
greeting.pack()
button.pack()
entry.pack()
frame = Frame(master=window, relief=RAISED, borderwidth=1)
frame.pack()
lbl = Label(master=frame, text="I'm in a frame")
lbl.pack()
textbox = Text(fg="green", bg="yellow")
textbox.pack()